# dataset
dataset: UCM
input_size: [224, 224]
num_classes: 21

# model
backbone: swin
hidden_dim: 1024

# transform
color_jitter: null
aa: rand-m9-mstd0.5-inc1
reprob: 0.25
remode: pixel
recount: 1
mixup: 0.8
cutmix: 1
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch
smoothing: 0.1

# optimizer
epochs: 200
optimizer: adan
lr: 0.003125
wd: 0.02
max_grad_norm: 0.

# scheduler
name: cosine
min_lr: 0.000001
warmup_epochs: 5
warmup_method: linear
warmup_factor: 0.01
decay_epochs: 30
decay_rate: 0.1
multisteps: []
gamma: 0.1